spring:
  application.name: easydrop
  datasource:
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    url: ${LOCAL_DB_URL}
  jpa:
    # auto create or update db tables based on @Entity classes
    hibernate.ddl-auto: update
    # logs SQL queries to console for debugging
    show-sql: true
